# Generated by Django 5.2.1 on 2025-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('title', models.CharField()),
                ('content', models.CharField()),
                ('id', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
    ]
