# Generated by Django 5.2.1 on 2025-06-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bfile',
            field=models.ImageField(blank=True, null=True, upload_to='custoemer'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='ffile',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
    ]
