# Generated by Django 5.2.1 on 2025-06-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_bfile_alter_customfile_ffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bfile2',
            field=models.ImageField(blank=True, null=True, upload_to='custoemer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
