# Generated by Django 5.2.1 on 2025-06-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_bdate_customer_bfile2_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='member',
        ),
    ]
