# Generated by Django 5.2.1 on 2025-06-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bfile2',
        ),
    ]
