# Generated by Django 5.2.1 on 2025-06-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_bfile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bfile2',
            field=models.ImageField(blank=True, null=True, upload_to='custoemer'),
        ),
    ]
