# Generated by Django 5.2.1 on 2025-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('monthly', models.CharField(max_length=10)),
                ('totalSales', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
            ],
        ),
    ]
