# Generated by Django 5.2.1 on 2025-05-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('pw', models.CharField()),
                ('nickname', models.CharField()),
                ('tel', models.CharField(default='010-0000-0000')),
                ('hobby', models.CharField()),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
