# Generated by Django 5.2.1 on 2025-06-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.CharField(default='aaa', max_length=100)),
                ('cpw', models.CharField(blank=True, max_length=20, null=True)),
                ('ccontent', models.TextField(blank=True)),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
