# Generated by Django 5.2.1 on 2025-06-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bdate',
            field=models.DateField(auto_now=True),
        ),
    ]
