# Generated by Django 5.2.1 on 2025-06-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
