# Generated by Django 5.2.1 on 2025-06-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bgroup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='bindent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='bstep',
            field=models.IntegerField(default=0),
        ),
    ]
