# Generated by Django 5.2.1 on 2025-06-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_bgroup_board_bindent_board_bstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bfile',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='bhit',
            field=models.IntegerField(default=0),
        ),
    ]
