# Generated by Django 5.2.1 on 2025-06-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('emailc', models.IntegerField(default=0)),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=300)),
                ('phone', models.CharField(default='010-0000-0000', max_length=50)),
                ('tel', models.CharField(default='02-0000-0000', max_length=50)),
                ('birth', models.CharField(max_length=20)),
                ('corporate', models.IntegerField(default=0)),
                ('gender', models.CharField(default='남자', max_length=10)),
                ('hobby', models.CharField(default='게임', max_length=50)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
