# Generated by Django 5.2.1 on 2025-06-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
