# Generated by Django 5.2.1 on 2025-05-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ageage',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
