# Generated by Django 5.2.1 on 2025-05-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('grade', models.IntegerField(max_length=1)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
