# Generated by Django 5.2.1 on 2025-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('bgroup', models.IntegerField(default=0)),
                ('bstep', models.IntegerField(default=0)),
                ('bindent', models.IntegerField(default=0)),
                ('bhit', models.IntegerField(default=0)),
                ('bfile', models.FileField(blank=True, null=True, upload_to='board')),
            ],
        ),
    ]
